# Generated by Django 5.2.8 on 2025-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='Kalhoro123', max_length=100),
        ),
    ]
